# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iLpXJ9M4TBh39lEqmbP7ku3NRfuH6yj
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split


salary = pd.read_csv('salary_data.csv')
# print(salary)

valores_base= salary[['lowest_salary', 'highest_salary']]


X_train, X_test, y_train, y_test = train_test_split(valores_base, salary.median_salary, test_size=0.25)

clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
clf = clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

print("\nMatriz de confusão detalhada:\n",
      pd.crosstab(y_test, predictions, rownames=['Real'], colnames=['Predito'],
      margins=True, margins_name='Todos'))