# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_e9h_qkfRxnY0eY-pmDLknnhlunoB4Ih
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import numpy as np


df = pd.read_csv('salary_data.csv')

features = df[['wage_span', 'median_salary', 'average_salary', 'lowest_salary']]
target = df['highest_salary']

features['wage_span'] = features['wage_span'].astype('category').cat.codes

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=0)

model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, predictions))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, predictions))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

coefficients = pd.DataFrame({'Feature': features.columns, 'Coefficient': model.coef_})
print('\nCoefficients:')
print(coefficients)

print('\nIntercept:', model.intercept_)